### ISSUE TITLE
关于metaclass=TimingMeta不解

### ISSUE THREAD

**Issue by dzzxjl** [carefree0910/MachineLearning#2]
请问TimingMeta类是什么意思啊？书上的版本没有

**Comment by carefree0910** [comment]
你好，metaclass是一个黑魔法，暂时只知道TimingMeta是辅助计时的工具就好~
不过如果确实想知道metaclass的相关知识的话，也可以参见我在知乎专栏中写的[这篇文章](https://zhuanlan.zhihu.com/p/24633374)~
