### ISSUE TITLE
报错如下

### ISSUE THREAD

**Issue by christ-280990** [carefree0910/MachineLearning#33]
我用的是tensorflow2.x版本 
这是出现在  _fully_connected_linear中的错误 在初始化权重的时候报错 
Traceback (most recent call last):
  File "D:\NNs_tensorflow\NNs.py", line 8, in <module>
    nn = Basic(model_param_settings={'n_epoch':100}).fit(x,y,snapshot_ratio=0)
  File "D:\NNs_tensorflow\Base.py", line 149, in fit
    self._build_model()
  File "D:\NNs_tensorflow\BasicNN.py", line 44, in _build_model
    net = self._fully_connected_linear(net, [current_dimension, n_unit], i)
  File "D:\NNs_tensorflow\Base.py", line 101, in _fully_connected_linear
    w = Toolbox.init_w(shape, "W{}".format(appendix))
  File "D:\NNs_tensorflow\NNUtil.py", line 224, in init_w
    return tf.Variable(tf.compat.v1.truncated_normal(shape,stddev=math.sqrt(2/sum(shape))),name=name)
TypeError: unsupported operand type(s) for +: 'int' and 'str'

**Comment by carefree0910** [comment]
这个当时是用的相当老的 tf 版本了，2.x 可能是兼容不了了🤣

**Comment by christ-280990** [comment]
哈哈哈 谢谢作者大大的回复 我已经找到问题了&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月24日(星期一) 晚上8:27
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [carefree0910/MachineLearning] 报错如下 (Issue #33)





 
这个当时是用的相当老的 tf 版本了，2.x 可能是兼容不了了🤣

**Comment by carefree0910** [comment]
哈哈好耶！🥳
