### ISSUE TITLE
module 'subprocess' has no attribute 'mswindows' in NN.py

### ISSUE THREAD

**Issue by 395062753** [carefree0910/MachineLearning#4]
在win10环境中运行NN.py出现错误，matplotlib==2.0.2 python3.6.5  tensorflow_gpu1.8 
安装PySide =1.1.1->1.2.4时出现module 'subprocess' has no attribute 'mswindows'，请问能在win10环境中运行么，

**Comment by carefree0910** [comment]
您好，我在 win10 下能运行，安装环境的问题可以尝试谷歌，谢谢！
